# Generated by Django 5.0.6 on 2024-06-16 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='Email',
        ),
    ]
