# Generated by Django 5.0.6 on 2024-06-16 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0002_remove_myuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrowed_by',
        ),
        migrations.DeleteModel(
            name='myUser',
        ),
    ]
